<?php

/**
 * Created by PhpStorm.
 * User: formation
 * Date: 11/04/17
 * Time: 09:27
 */

namespace Training\Helloworld\Rewrite\Model;

class Product extends \Magento\Catalog\Model\Product
{

     public function getName()
     {
         return parent::getName(). ' Hello world'; // TODO: Change the autogenerated stub
     }
}